[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
trading_vault = "4aeW1288H4t5oSmUhmrxmVfvuhFgYrtPSj6BGwCC4djv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/wsl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
